import './js/current_link';
import './js/profile';
import './js/getBySearch.js';
import './js/film-modal';
import './js/addMoviesInLibrary';
import './js/pagination';
import './js/scroll-button';
import { getByVideo } from './js/getById';
getByVideo();
import AOS from 'aos';
import 'aos/dist/aos.css';
AOS.init();
